#!/usr/bin/env python
import time
from datetime import datetime
from chomsky import db
from chomsky.db import Article
from chomsky import histos
from chomsky import viz

CNN_COLOR = '#911131'

if __name__ == '__main__':
    query = db.session.query(Article)
    articles = query.filter(Article.added>datetime(2011,3,14,18))
    histograms = histos.histograms(artxbicles)
    aggregate = histos.aggregate_counts(histograms,  sort=True)

    viz.bar_chart(aggregate, sample_size=12, color=CNN_COLOR, 
                  title='Word Usage - %s' % time.strftime('%d-%m-%Y') )
